name=@extname@
description=A Ghidra loader for Microsoft's USB Flashing Format (UF2). Supports ARM Cortex, Xtensa (ESP32/ESP8266), RISC-V (ESP32-C3), and AVR8 architectures. Features contiguous block merging and FileBytes support.
author=wyattearp
createdOn=Jul 23, 2021
version=@extversion@
